export type ICompanyValue = string | null;

export interface ICompany {
  id: ICompanyValue,
  ticker: ICompanyValue,
  name: ICompanyValue,
  lei: ICompanyValue,
  legal_name: string,
  stock_exchange: string,
  sic: number,
  short_description: string;
  long_description: string;
  ceo: string,
  company_url: string,
  business_address: string,
  mailing_address: string,
  business_phone_no: string,
  hq_address1: ICompanyValue,
  hq_address2: null,
  hq_address_city: string | null,
  hq_address_postal_code: ICompanyValue,
  entity_legal_form: null,
  cik: number | null,
  latest_filing_date: Date,
  hq_state: ICompanyValue,
  hq_country: ICompanyValue,
  inc_state: ICompanyValue,
  inc_country: ICompanyValue,
  employees: number,
  entity_status: null,
  sector: ICompanyValue,
  industry_category: ICompanyValue,
  industry_group: ICompanyValue,
  template: ICompanyValue,
  standardized_active: true,
  first_fundamental_date: Date,
  last_fundamental_date: Date,
  first_stock_price_date: Date,
  last_stock_price_date: Date,
  thea_enabled: boolean,
  legacy_sector: ICompanyValue,
  legacy_industry_category: ICompanyValue,
  legacy_industry_group: ICompanyValue
}